trigger:
- main

pool:
  name: 'Azure-Pipelines'  # Specify your custom agent pool name

steps:
- checkout: self

- script: |
    echo "Building the project..."
    # Install Apache if needed
    sudo apt-get update
    sudo apt-get install -y apache2
    sudo systemctl start apache2
    sudo systemctl enable apache2
    # Deploy project files
    sudo cp -r * /var/www/html/
  displayName: 'Build and Deploy'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '/var/www/html'
    artifactName: 'webapp'
    publishLocation: 'Container'
